### ISSUE TITLE
Cant upload files when right click and select "Upload"

### ISSUE THREAD

**Issue by sharezomics** [coderaiser/cloudcmd#113]
Files do not upload from the local machine (says 100% but never completes) when I right click on the file manager in the browser and select "Upload" > "Choose Files" from the drop-down menu.

Files correctly upload if I right click on the file manager in the browser and select "Upload from Cloud" > "Drag file here" or "Choose File".

* **Version** (`cloudcmd -v`): 6.90
* **Node Version** `node -v`: 6.9.2
* **OS** (`uname -a` on Linux): 
Alpine Linux 3.5 docker container in xubuntu 14.04 Virtualbox VM on Windows 10 host.  
uname -a results:"Linux 990fe54ad1a7 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 Linux".
* **Browser name/version**: Chrome Version 57.0.2987.133 (64-bit)/FireFox Version 52.0.1

**Comment by coderaiser** [comment]
Thank you, fixed with d59c998. Landed in [v6.9.1](https://github.com/coderaiser/cloudcmd/releases/tag/v6.9.1).

**Comment by sharezomics** [comment]
I've updated to v6.9.1 but am still getting the same problem.

**Comment by coderaiser** [comment]
Could you please clear cache of your browser, open developer tools and check if some red errors present in console or in network panel when you trying to upload a file?

**Comment by sharezomics** [comment]
Ok. Testing with Firefox 52.0.1, I have noticed that:

a) If I try to upload a small text file after opening cloud commander 'undefined' gets pre-pended to the file name. If I repeat the upload, it then gets properly transferred with the correct file name (ie undefined is not prepended).
b)anything larger than 1mb does not upload. (error: "Request Entity Too Large")

Below is the console output for the following events: 
1)upload "DxDiag.txt" (<1mb)
2)re-upload "DxDiag.txt" (<1mb)
3)upload "HFS_update_Jan-Mar_2017.pdf" (<1mb)
4)upload "dillon 2013 Genetic diversity of the Australian National Mango Genebank.pdf" (>1mb)

##############################################################################

PUT 
XHR 
http://192.168.0.105:8000/api/v1/fsundefinedDxDiag.txt [HTTP/1.1 200 OK 4ms]
Headers
POST
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-Length31Content-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveContent-Length77411Content-Typetext/plainHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/api/v1/fs/ [HTTP/1.1 200 OK 4ms]
Headers
Params
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-EncodinggzipContent-Length148Content-Typeapplication/json; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/tmpl/fs/file.hbs [HTTP/1.1 200 OK 8ms]
Headers
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=658077Connectionkeep-aliveContent-EncodinggzipContent-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTLast-ModifiedMon, 05 Sep 2016 11:40:53 GMTServernginx/1.10.3Transfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/tmpl/fs/path.hbs [HTTP/1.1 200 OK 9ms]
Headers
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=658077Connectionkeep-aliveContent-EncodinggzipContent-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTLast-ModifiedMon, 05 Sep 2016 11:40:53 GMTServernginx/1.10.3Transfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/tmpl/fs/link.hbs [HTTP/1.1 200 OK 9ms]
Headers
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=658077Connectionkeep-aliveContent-EncodinggzipContent-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTLast-ModifiedMon, 05 Sep 2016 11:40:53 GMTServernginx/1.10.3Transfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/tmpl/fs/pathLink.hbs [HTTP/1.1 200 OK 10ms]
Headers
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=658077Connectionkeep-aliveContent-EncodinggzipContent-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:01:30 GMTLast-ModifiedMon, 05 Sep 2016 11:40:53 GMTServernginx/1.10.3Transfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
http://192.168.0.105:8000/img/txt.png [HTTP/1.1 200 OK 5ms]
Headers
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=658077Connectionkeep-aliveContent-EncodinggzipContent-Typeimage/pngDateFri, 14 Apr 2017 04:01:30 GMTLast-ModifiedMon, 05 Sep 2016 11:40:53 GMTServernginx/1.10.3Transfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/css/urls.cssUser-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

PUT 
XHR 
http://192.168.0.105:8000/api/v1/fs/DxDiag.txt [HTTP/1.1 200 OK 4ms]
Headers
POST
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-Length22Content-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:02:11 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveContent-Length77411Content-Typetext/plainHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/api/v1/fs/ [HTTP/1.1 200 OK 3ms]
Headers
Params
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-EncodinggzipContent-Length154Content-Typeapplication/json; charset=UTF-8DateFri, 14 Apr 2017 04:02:11 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

PUT 
XHR 
http://192.168.0.105:8000/api/v1/fs/HFS_update_Jan-Mar_2017.pdf [HTTP/1.1 200 OK 6ms]
Headers
POST
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-Length39Content-Typetext/plain; charset=UTF-8DateFri, 14 Apr 2017 04:02:48 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveContent-Length359518Content-Typeapplication/pdfHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

GET 
XHR 
http://192.168.0.105:8000/api/v1/fs/ [HTTP/1.1 200 OK 4ms]
Headers
Params
Response
Call Stack
Accept-RangesbytesAccess-Control-Allow-Origin*Cache-Controlmax-age=0Connectionkeep-aliveContent-EncodinggzipContent-Length189Content-Typeapplication/json; charset=UTF-8DateFri, 14 Apr 2017 04:02:48 GMTServernginx/1.10.3VaryAccept-EncodingX-Powered-ByExpress
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

PUT 
XHR 
http://192.168.0.105:8000/api/v1/fs/dillon%202013%20Genetic%20diversity%20of%20the%20Australian%20National%20Mango%20Genebank.pdf [HTTP/1.1 413 Request Entity Too Large 4ms]
Headers
POST
Response
Call Stack
ConnectioncloseContent-Length199Content-Typetext/htmlDateFri, 14 Apr 2017 04:03:30 GMTServernginx/1.10.3
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveContent-Length1202478Content-Typeapplication/pdfHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

Error: <html>

<head><title>413 Request Entity Too Large</title></head>

<body bgcolor="white">

<center><h1>413 Request Entity Too Large</h1></center>

<hr><center>nginx/1.10.3</center>

</body>

</html>

  cloudcmd.js:1:6927
	t.exports.put/n.onreadystatechange http://192.168.0.105:8000/cloudcmd.js:1:6927 
 
 
##############################################################################

**Comment by coderaiser** [comment]
Looks like, last error is related to [nginx](https://nginx.org/) config option: [client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) and it can be increased.

```
PUT 
XHR 
http://192.168.0.105:8000/api/v1/fs/dillon%202013%20Genetic%20diversity%20of%20the%20Australian%20National%20Mango%20Genebank.pdf [HTTP/1.1 413 Request Entity Too Large 4ms]
Headers
POST
Response
Call Stack
ConnectioncloseContent-Length199Content-Typetext/htmlDateFri, 14 Apr 2017 04:03:30 GMTServernginx/1.10.3
Accept*/*Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5AuthorizationBasic Y2xvdWQ6Y29tbWFuZGVyConnectionkeep-aliveContent-Length1202478Content-Typeapplication/pdfHost192.168.0.105:8000Refererhttp://192.168.0.105:8000/User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

Error: <html>

<head><title>413 Request Entity Too Large</title></head>

<body bgcolor="white">

<center><h1>413 Request Entity Too Large</h1></center>

<hr><center>nginx/1.10.3</center>

</body>

</html>

  cloudcmd.js:1:6927
	t.exports.put/n.onreadystatechange http://192.168.0.105:8000/cloudcmd.js:1:6927 
```

Could you please try one of those:

- open `chrome` or `firefox` in incognito mode
- try to reproduce it on the current demo page: `http://cloudcmd.herokuapp.com/` -
- try to [deploy new instance to heroku](https://heroku.com/deploy?template=https://github.com/coderaiser/cloudcmd).

As I see from this line:

```
http://192.168.0.105:8000/api/v1/fsundefinedDxDiag.txt [HTTP/1.1 200 OK 4ms]
```

Your cache is not updated. Have you cleared it?
You can also turn of `Cache` checkbox in `Config` and reload the page.

**Comment by sharezomics** [comment]
Thanks for identifying the nginx issue (I should have realised). All fixed for that.

I can't reproduce the problem with 'undefined' being prepended to initially uploaded files in cloudcmd at http://cloudcmd.herokuapp.com/.

It only occurs on my system (alpine linux in docker) if a file does not already exist in the folder that I'm uploading to. 

If I start cloudcmd with the following script:

`cd /home
touch ./thisFilePreventsUndefinedError.txt
node /usr/src/app/node_modules/cloudcmd/bin/cloudcmd --root /home --auth -u cloud -p commander --save`

...I don't get the issue. Perhaps that will do for a workaround for now.......

Still happens with a fully cleared cache.

Will look into deploying a new instance to heroku (maybe could set up a repository on docker hub for reproducing the error).

Thanks for your help!

**Comment by sharezomics** [comment]
Attached is an archive that can be launched with docker-compose to replicate the problem (hopefully) with 'undefined' being prepended to the first uploaded file.

[cloud_commander_v6.9.1_docker_compose.tar.gz](https://github.com/coderaiser/cloudcmd/files/925178/cloud_commander_v6.9.1_docker_compose.tar.gz)

**Comment by coderaiser** [comment]
> It only occurs on my system (alpine linux in docker) if a file does not already exist in the folder that I'm uploading to.

I can reproduce a bug when I set option `--root` with an empty directory. I will think about it, thank you.

**Comment by coderaiser** [comment]
Fixed with 7b240ca, landed in [v6.9.3](https://github.com/coderaiser/cloudcmd/releases/tag/v6.9.3).

**Comment by sharezomics** [comment]
Thank you!
