### ISSUE TITLE
Error on copying large folders

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#285]
* **Version** : v14.3.8 (tested it on older v14 release as well)
* **Node Version**: v12.16.2  
* **OS**: ubuntu 18
* **Browser name/version**: Chrome v80.0.3987.132 

While copying larger folders with a lot of files and subfolders I often run into this error:

```
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '[random-subfolder-at-target-location]'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy ([project_home]/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at WriteStream.onerror ([project_home]/node_modules/readable-stream/lib/_stream_readable.js:704:47)
    at WriteStream.emit (events.js:310:20)
    at internal/fs/streams.js:321:12
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '[random-subfolder-at-target-location]'
}
```
Tried copying the same folder multiple times it seems to happen at a different folder every time.

**Comment by coderaiser** [comment]
What do you mean by large folders? I just copied `node_modules` with size `300MB`, it contains a lot files :). And everything works good.

**Comment by csazku** [comment]
You are right, I should have given you an example as well. :)
I downloaded magento 2 from github ( https://github.com/magento/magento2/archive/2.4-develop.zip ), started up cloudcmd without any config and tried copying the `magento2-2.4-develop` folder from `Downloads` to `Pictures`.
That gives me an error every time.

**Comment by coderaiser** [comment]
Unfortunately I still can't reproduce this, everything works for me

**Comment by csazku** [comment]
Updated npm, deleted all my global node modules and did a clean install of cloudcmd, ran it as root, tried it with chorme and firefox just to be sure, but it's still happening, will try to investigate it further next week.

**Comment by coderaiser** [comment]
Could you please try to use `node v13` and `node v10`, is behavior reproducible?

**Comment by csazku** [comment]
Slightly different error message on  v10/v13 but it still happens.
 
on v13:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '[homedir]/Pictures/magento2-2.4-develop/dev/tests/integration/testsuite/Magento/Theme/Model/_files/design/design_area/Vendor/theme_one/web'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '[homedir]/Pictures/magento2-2.4-develop/dev/tests/integration/testsuite/Magento/Theme/Model/_files/design/design_area/Vendor/theme_one/web'
}
```
-------------------------------------------------------------------------------------------
on v10:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '[homedir]/Pictures/magento2-2.4-develop/dev/tests/functional/tests/app/Magento/Weee/Test/Block/Adminhtml/Product/Edit/Section'
Emitted 'error' event at:
    at errorOrDestroy (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at WriteStream.onerror (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_readable.js:704:47)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

```

**Comment by csazku** [comment]
Back with an update:
Installed cloudcmd on a clean vps, running it with node 12 as root.
Copying `magento2-2.4-develop` form `/root` to `/home`.
For the first 5-6 times it worked however after that the error started appearing.
Before copying again I always delete the `magento2-2.4-develop` form `/home`
Tried it with v14.3.10 as well.

**Comment by coderaiser** [comment]
@csazku  Could you please is it the same partition or different? What file system do you use?

**Comment by csazku** [comment]
I'm using ext4 on both my local setup and on the test vps, the source and destination folders are on the same partition.

**Comment by coderaiser** [comment]
Let's try one thing. Cloud Commander uses module [copymitter](https://github.com/coderaiser/node-copymitter) for copying. Let's try to use it directly with:

```
npm i copymitter --save
```

Then create a file and set `from` and `to`: 

```js
const copymitter = require('copymitter');

const from = 'directory contains magento'
const to = 'new magento location';

const cp = copymitter(from, to, [
    'magento2-2.4-develop'
]);

cp.on('file', (from, to) => {
    console.log(`${from} -> ${to}`);
});

cp.on('directory', (from, to) => {
    console.log(`${from} -> ${to}`);
});

cp.on('progress', (percent) => {
    console.log(percent);
});

cp.on('error', (error) => {
    console.error(error);
});

cp.on('end', () => {
    console.log('Copying ended up');
});
```

**Comment by csazku** [comment]
Ran it a few times, here are 2 results, output ended up being a few mb so i had to zip it.
https://drive.google.com/open?id=1rO03WjzrKGvKentKOK9NK5cdtV2rbtQf

**Comment by coderaiser** [comment]
Fixed operations order with https://github.com/coderaiser/node-copymitter/commit/760630a915bc1f8a852bc8ca3bb208ab22cd43c8. Landed in [copymitter v5.0.4](https://github.com/coderaiser/node-copymitter/releases/tag/v5.0.4) :tada: . Could you please try again with a new version?

**Comment by csazku** [comment]
Ran the script again, the error is still there, here are 2 more results:
https://drive.google.com/open?id=1Nt2HfQqZAclTPSv7q024gaUJQVHWpxK3
Tried with v5.0.4 and v5.0.5 as well.

**Comment by coderaiser** [comment]
I had a chance to reproduce this behavior on Mac OS. And the problem was in more deeper module :), is `pipe-io`.

So I fixed 🔨with https://github.com/coderaiser/pipe-io/commit/18b527be4fc5544b30341e81903896db7971b5d7. Landed in [pipe-io v4.0.4](https://github.com/coderaiser/pipe-io/releases/tag/v4.0.1) 🎉. Now the bottom layer of Cloud Commander became a little bit more reliable :). Is it works for you?

**Comment by csazku** [comment]
Tested it twice with the script and 5 times in cloudcmd, it's working now.
Thank you!
