### ISSUE TITLE
Smalltalk dialog doesn't disappear

### ISSUE THREAD

**Issue by baldemir** [coderaiser/cloudcmd#295]
I'm trying to use cloudcmd as middleware as shown in README. When I want to copy a file from one path to another by drag-drop it shows progress dialog and it never disappears. When I refresh I see that file is copied as expected. Same thing happens when I try to delete file by right click. Any idea why i'm experiencing this? 

Thanks in advance. 

* **Version** (`cloudcmd -v`): 14.9.2
* **Node Version** `node -v`: 14.8.0
* **OS** (`uname -a` on Linux): macOS 10.14.6
* **Browser name/version**: Chrome 84.0.4147.125

**Comment by baldemir** [comment]
Ok I checked and it works as expected now. Thank you. Heroku app is currently not working. Do you plan a fix for that? @coderaiser

**Comment by coderaiser** [comment]
@baldemir that's amazing. I have no idea why `heroku` not working, I will be glad for help.

**Comment by coderaiser** [comment]
@baldemir `heroku` demo should work now :) 🎉

**Comment by baldemir** [comment]
Hi @coderaiser I confirmed my issue about refresh on drag and drop it still continues. Sometimes it works but mostly it doesn't. I'm able to reproduce it on heroku instance too. Any idea why it happens?

https://gyazo.com/6d8ef677667966b64f656f49ff6ef26c

**Comment by coderaiser** [comment]
Hi @baldemir, looks like the problem with [copymitter](https://github.com/coderaiser/node-copymitter) and 0 size files:

https://github.com/coderaiser/node-copymitter/blob/v5.0.6//lib/copymitter.js#L62
https://github.com/coderaiser/node-copymitter/blob/v5.0.6/lib/copymitter.js#L218

**Comment by baldemir** [comment]
Ok thanks @coderaiser for looking into that!

**Comment by coderaiser** [comment]
@baldemir fixed with https://github.com/coderaiser/node-copymitter/commit/80312ecf616b1c72dc5a13353ba3fb00b0906a10, landed in [copymitter v5.0.7](https://github.com/coderaiser/node-copymitter/releases/tag/v5.0.7) 🎉 . Is it works for you?

**Comment by baldemir** [comment]
Works like a charm 🎉  Thanks @coderaiser
