### ISSUE TITLE
Upload stuck for zero byte files

### ISSUE THREAD

**Issue by kucerajo** [coderaiser/cloudcmd#359]
- **Version** (`cloudcmd -v`): 15.9.9
- **Node Version** `node -v`: xxx
- **OS** (`uname -a` on Linux): xxx
- **Browser name/version**: Chrome 97.0.4692.36
- **Used Command Line Parameters**: xxx
- **Changed Config**: xxx

The upload is stuck when zero byte file is uploaded.
In the end, the file is created in the Cloud commander but the uploaded must be manually aborted...
Please see attached screenshots.
Thank you!

![image](https://user-images.githubusercontent.com/95855716/145383833-df277a98-1f37-47a1-ba9f-607d661bf465.png)

![image](https://user-images.githubusercontent.com/95855716/145383878-9be98b77-5b9b-43f5-9b71-4c08392785ba.png)

**Comment by coderaiser** [comment]
Could you please tell me why do you need to upload zero byte files?

**Comment by coderaiser** [comment]
Fixed with ed14250, landed in [v15.9.11](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.11) 🎉 . Is it works for you?

**Comment by kucerajo** [comment]
> Could you please tell me why do you need to upload zero byte files?

:) I know that it could look a little bit weird but there still exist many reasons to do it. For example we use this tool beside our application in K8S to simulate filesystem in DEV and TEST environments to easily access it via web browser. In our case, we simulate FTP upload to our application (like in PROD) and the successful and final upload is confirmed via creation of zero-byte file with the same name and added extension .cnf.

> Fixed with [ed14250](https://github.com/coderaiser/cloudcmd/commit/ed14250fe228a8605954d91dc5dede2dd7cd2744), landed in [v15.9.11](https://github.com/coderaiser/cloudcmd/releases/tag/v15.9.11) 🎉 . Is it works for you?

Thank you very much this fast fix! We will test it and let you know :)
